name: Sync to S3 bucket

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  sync:
    name: Sync to S3 CDN
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'update cdn') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: |
          aws s3 sync ./ s3://$AWS_PATH --exclude ".git/*"
        env:
          AWS_PATH: ${{ secrets.AWS_PATH }}